version: 2.1

commands:
  setup_sbt:
    description: Get and install SBT
    parameters:
      sbt_version:
        type: string
        default: "1.5.5"
    steps:
      - restore_cache:
          keys:
          - &sbt_cache_key sbt-{{ checksum "project/build.properties" }}

      - run:
          name: Setup SBT
          command: |
                    if [ ! -x ~/sbt/bin/sbt ]; then
                      cd ~/
                      curl --silent -L -o sbt.tgz https://github.com/sbt/sbt/releases/download/v<< parameters.sbt_version >>/sbt-<< parameters.sbt_version >>.tgz
                      tar -xzvf sbt.tgz && rm -f sbt.tgz
                    fi

      - save_cache:
          paths:
            - ~/sbt
          key: *sbt_cache_key

  build_n_tests:
    description: Build & Run tests
    steps:
      - restore_cache:
          keys:
          - &scala_cache_key scala-{{ .Environment.CIRCLE_JOB }}-{{ checksum "version.sbt" }}-{{ checksum "build.sbt" }}

      - run:
          name: Build & Run tests
          command: |
                    export PATH=$PATH:~/sbt/bin
                    
                    ./.ci_scripts/validate.sh

      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.coursier/cache
            - ~/.sbt
          key: *scala_cache_key

  collect_test_reports:
    description: Collect test reports
    steps:
      - run:
          name: Collect test report
          command: |
                    mkdir test-reports
                    find . -path '*/test-reports/*' -name '*.xml' \
                      -print -exec cp {} test-reports \;
          when: always

jobs:
  scala211_jdk8:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.11.12
    
    steps:
      - checkout
      - setup_sbt
      - build_n_tests
      - collect_test_reports
      - store_test_results:
          path: test-reports

  scala212_jdk8:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.12.15
    
    steps:
      - checkout
      - setup_sbt
      - build_n_tests
      - collect_test_reports
      - store_test_results:
          path: test-reports

  scala213_jdk8:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.13.7
    
    steps:
      - checkout
      - setup_sbt
      - build_n_tests
      - collect_test_reports
      - store_test_results:
          path: test-reports

  scala212_jdk9:
    docker:
      - image: circleci/openjdk:9-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.12.15
    
    steps:
      - checkout
      - setup_sbt
      - build_n_tests
      - collect_test_reports
      - store_test_results:
          path: test-reports

  scala213_jdk11:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.13.7
    
    steps:
      - checkout
      - setup_sbt
      - build_n_tests
      - collect_test_reports
      - store_test_results:
          path: test-reports

workflows:
  version: 2

  main_suite:
    jobs:
      - scala211_jdk8
      - scala212_jdk8
      - scala213_jdk8
      - scala212_jdk9
      - scala213_jdk11
