name: Check

on:
  pull_request:

  push:
    branches:
      - main # Check branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-style:
    name: Code Style
    uses: playframework/.github/.github/workflows/cmd.yml@v4
    with:
      cmd: sbt validateCode

  check-binary-compatibility:
    name: Binary Compatibility
    uses: playframework/.github/.github/workflows/binary-check.yml@v4

  check-docs-8:
    name: Docs Java 8
    uses: playframework/.github/.github/workflows/cmd.yml@v4
    with:
      java: 8
      scala: 2.11.x, 2.12.x
      cmd: sbt ++$MATRIX_SCALA docs/test

  check-docs-11:
    name: Docs
    uses: playframework/.github/.github/workflows/cmd.yml@v4
    with:
      java: 11
      scala: 2.11.x, 2.12.x, 2.13.x, 3.x
      cmd: sbt ++$MATRIX_SCALA docs/test

  tests-8:
    name: Tests
    needs:
      - "check-code-style"
      - "check-binary-compatibility"
      - "check-docs-8"
    uses: playframework/.github/.github/workflows/cmd.yml@v4
    with:
      java: 8
      scala: 2.11.x, 2.12.x
      cmd: sbt ++$MATRIX_SCALA publishLocal test

  tests-11:
    name: Tests
    needs:
      - "check-code-style"
      - "check-binary-compatibility"
      - "check-docs-11"
    uses: playframework/.github/.github/workflows/cmd.yml@v4
    with:
      java: 11
      scala: 2.11.x, 2.12.x, 2.13.x, 3.x
      cmd: sbt ++$MATRIX_SCALA publishLocal test

  finish:
    name: Finish
    if: github.event_name == 'pull_request'
    needs: # Should be last
      - "tests-8"
      - "tests-11"
    uses: playframework/.github/.github/workflows/rtm.yml@v4
