name: Check

on:
  pull_request:

  push:
    branches:
      - 2.7.x # Check branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-style:
    name: Code Style
    uses: playframework/.github/.github/workflows/cmd.yml@v2
    with:
      cmd: sbt validateCode

  check-binary-compatibility:
    name: Binary Compatibility
    uses: playframework/.github/.github/workflows/binary-check.yml@v2

  check-docs:
    name: Docs
    uses: playframework/.github/.github/workflows/cmd.yml@v2
    with:
      java: 11, 8
      scala: 2.11.12, 2.12.16, 2.13.8 # TODO: 3.1.3 (other play modules not ok)
      cmd: sbt ++$MATRIX_SCALA docs/test

  tests:
    name: Tests
    needs:
      - "check-code-style"
      - "check-binary-compatibility"
      - "check-docs"
    uses: playframework/.github/.github/workflows/cmd.yml@v2
    with:
      java: 11, 8
      scala: 2.11.12, 2.12.16, 2.13.8, 3.1.3
      cmd: sbt ++$MATRIX_SCALA publishLocal test

  finish:
    name: Finish
    if: github.event_name == 'pull_request'
    needs: # Should be last
      - "tests"
    uses: playframework/.github/.github/workflows/rtm.yml@v2
